### PR TITLE
Bug fix #170

### LINKED ISSUE #170: [BUG](Protocol.UndefinedError) protocol String.Chars not implemented for
**Versions Used**
Kaffy: master branch
Phoenix: 1.5.6
Elixir: 1.10.4

**What's actually happening?**
`(Protocol.UndefinedError) protocol String.Chars not implemented for` is raised when validation fails on a form with an embedded schema.

**What should happen instead?**
Show form with validation error messages instead.

### PR DESCRIPTION
**Pull request by gushonorato**
Closes #170

### CODE REVIEW

File: lib/kaffy/resource_form.ex [hunk 1]
```diff
@@ -335,6 +335,10 @@ defmodule Kaffy.ResourceForm do
       nil ->
         {nil, ""}
 
+      # # In case of field is a embedded schema
+      %{} ->
```
Comment (manuel-rubio) [inline lib/kaffy/resource_form.ex:339]: If you want to match a schema, use better `%_{}` to ensure it's matching against a struct and not a map.

Comment (gushonorato) [reply lib/kaffy/resource_form.ex:339]: Actually, the comment is wrong. It was my intention to match maps too. Thanks!
